### ISSUE TITLE
Wifi Configuration

### ISSUE THREAD

**Issue by vespassassina** [makerbase-mks/MKS-Robin-Nano#1]
How do i configure and use WIFI ?

**Comment by makerbase-mks** [comment]
Set the wifi mode, wifi name, and wifi password in the configuration file (robin_nano_cfg.txt) to use.
![image](https://user-images.githubusercontent.com/12979070/70409172-cff2f480-1a85-11ea-8de1-7aaabf17440a.png)

**Comment by vespassassina** [comment]
Perfect
