### ISSUE TITLE
 MKS Robin Nano TMC 2209 v 3.0 UART how is install ?

### ISSUE THREAD

**Issue by dejavuxer** [makerbase-mks/MKS-Robin-Nano#18]
Hi friend. 

Sorry for my broken English. I have two trees bluer 3d printer.
There are 2 TMC 2208 and 2 A4998 on it. Can I replace it with the TMC 2209 v3 uart I have? 

Can you tell me how to do it? 
Can you give information about the software and installation. 
Should I take action on the config file?

Thank you.

**Comment by Teslafly** [comment]
The uart pins are not connected correctly to the pins on the tmc2209 drivers. I am also trying to do this. 
you will need to use the wifi (or other) uart port and run it to the tmc drivers configured on different addresses using the microstepping jumpers, the uart will be connected to the slp pins direct to rx, and to tx through a 1k resistor.
I may post here if i get my setup working. 

this would not be hard to implement in a hardware revision. 
If they did, i would suggest adding jumpers to support native usb too.

**Comment by makerbase-mks** [comment]
1. You can use an IO to drive the TMC2208 / 2209 UART mode; UART_TX = UART_RX
2. You can connect to the free pin of the WIFI module to drive the TMC UART

**Comment by GrumpaV2** [comment]
Good so WiFi will still work then. Has this been tested?

**Comment by makerbase-mks** [comment]
Because you use marlin2.0, robin wifi is not available, so wifi IO can be used for TMC uart
