### ISSUE TITLE
How to configure 2208 Driver

### ISSUE THREAD

**Issue by vespassassina** [makerbase-mks/MKS-Robin-Nano#2]
I need to replace the existing drivers with 2208, how do i configure the firmware and hardware to use them ?

**Comment by makerbase-mks** [comment]
Hi, no setup required, just plug it in and use

**Comment by MowMoney** [comment]
> Hi, no setup required, just plug it in and use

Will this work with 2208 v3.0 IN UART? 
I can adjust my VREF and switch between speadcycle and silent modes on my display with my SKR boards. I hope to have this ability with my Robin Nano as well. 

Thank you

**Comment by makerbase-mks** [comment]
OK, thank your suggestion！
