### ISSUE TITLE
Nozzle fan.

### ISSUE THREAD

**Issue by fenoloji** [makerbase-mks/MKS-Robin-Nano#33]
Can three nozzle fans be connected to this socket(PB1)?
Each fan works with 50mA current. Total 150mA.
![Ekran Resmi 2020-06-18 12 58 07](https://user-images.githubusercontent.com/5780381/85007244-ee882580-b163-11ea-971b-052736f36715.png)

**Comment by makerbase-mks** [comment]
Hi! This is no problem.

**Comment by fenoloji** [comment]
Thank you..
