### ISSUE TITLE
STA Disconnected

### ISSUE THREAD

**Issue by dgorbunov** [makerbase-mks/MKS-Robin-Nano#43]
I finally got the WiFi module to connect to my WiFi on my Robin Nano V1.2 and if I go into WiFi settings it shows an IP, the network SSID, but says STA disconnected and occasionally throws an STA exception. Any idea why? The network is a normal 2.4GHz network, and I've been able to get it connected to my phone's hotspot but not my actual WiFi network.

**Comment by Sergey-Afonin** [comment]
It usually happenes if you have DIY WiFi module or previously fully erased WiFi module flash. Is it?

**Comment by dgorbunov** [comment]
Make sure your router settings allow for ports to opened on the network. This fixed it for me.
