### ISSUE TITLE
Mks Robin Nano ,Why  mks firmware can't play buzzer with M300 gcode?

### ISSUE THREAD

**Issue by fenoloji** [makerbase-mks/MKS-Robin-Nano#5]
I have Two trees bluer and it's mks firmware 1.0.3
I send gcode M300 but can't play buzzer.
However load Marlin firmware, it's play buzzer with gcode M300.
Mks firmware is bug.
How to solve?

**Comment by makerbase-mks** [comment]
1. First, the motherboard only installs an active buzzer; it can only be turned on or off, and cannot be controlled by frequency;
2. Of course, you can add control buzzer switch……
3. If you have the programming ability, you can also add the switch buzzer function by yourself, Nano motherboard source code: https://github.com/makerbase-mks/MKS-Robin-Nano-Firmware
